stages:
  process_data:
    cmd: |
      poetry run python src/data/process_data.py
      git commit -am "🔄 Auto-update processed data on $(date)" || exit 0
      git push || exit 0
      dvc push || exit 0
    deps:
      - src/data/process_data.py
      - data/raw/students_scores.csv
      - data/raw/students.xlsx
    outs:
      - data/processed/current_data.csv
    always_changed: true

  validate_data:
    cmd: poetry run python src/validation/validate_data.py
    deps:
      - src/validation/validate_data.py
      - data/processed/current_data.csv

  data_drift:
    cmd: poetry run python src/data/drift_report.py
    deps:
      - src/data/drift_report.py
      - data/processed/current_data.csv
      - data/processed/reference_dataset.csv
    outs:
      - reports/data_drift_report.html

  stability_tests:
    cmd: poetry run python src/data/stability_tests.py
    deps:
      - src/data/stability_tests.py
      - data/processed/current_data.csv
      - data/processed/reference_dataset.csv
    outs:
      - reports/stability_tests_report.html

  train_model:
    cmd: poetry run python src/models/train_eval.py
    deps:
      - src/models/train_eval.py
      - data/processed/current_data.csv
    outs:
      - models/model.pkl